
import { Language } from '@/types';

export const translations: Record<string, Record<Language, string>> = {
  // General & Common
  'it hub center': { en: 'IT Hub Center', it: 'IT Hub Center', es: 'IT Hub Center' },
  'enterprise it ops management': { en: 'Enterprise IT Operations Management', it: 'Gestione Operazioni IT Aziendali', es: 'Gestión de Operaciones de TI Empresariales' },
  'welcome': { en: 'Welcome!', it: 'Benvenuto!', es: '¡Bienvenido!' },
  'loading': { en: 'Loading...', it: 'Caricamento...', es: 'Cargando...' },
  'search': { en: 'Search', it: 'Cerca', es: 'Buscar' },
  'cancel': { en: 'Cancel', it: 'Annulla', es: 'Cancelar' },
  'delete': { en: 'Delete', it: 'Elimina', es: 'Eliminar' },
  'edit': { en: 'Edit', it: 'Modifica', es: 'Editar' },
  'save': { en: 'Save', it: 'Salva', es: 'Guardar' },
  'save changes': { en: 'Save Changes', it: 'Salva Modifiche', es: 'Guardar Cambios' },
  'close': { en: 'Close', it: 'Chiudi', es: 'Cerrar' },
  'all': { en: 'All', it: 'Tutti', es: 'Todos' },
  'all types': { en: 'All Types', it: 'Tutti i tipi', es: 'Todos los tipi' },
  'all users': { en: 'All Users', it: 'Tutti gli Utenti', es: 'Todos los Usuarios' },
  'all categories': { en: 'All Categories', it: 'Tutte le Categorie', es: 'Todas las Categorías' },
  'all years': { en: 'All Years', it: 'Tutti gli Anni', es: 'Todos los Años' },
  'all months': { en: 'All Months', it: 'Tutti i Mesi', es: 'Todos los Meses' },
  'all days': { en: 'All Days', it: 'Tutti i Giorni', es: 'Todos los Días' },
  'all statuses': { en: 'All Statuses', it: 'Tutti gli Stati', es: 'Todos los Estados' },
  'year': { en: 'Year', it: 'Anno', es: 'Año' },
  'month': { en: 'Month', it: 'Mese', es: 'Mes' },
  'day': { en: 'Day', it: 'Giorno', es: 'Día' },
  'none': { en: 'None', it: 'Nessuno', es: 'Ninguno' },
  'details': { en: 'Details', it: 'Dettagli', es: 'Detalles' },
  'actions': { en: 'Actions', it: 'Azioni', es: 'Acciones' },
  'by author': { en: 'by {author}', it: 'di {author}', es: 'por {author}' },
  'unknown author': { en: 'Unknown Author', it: 'Autore Sconosciuto', es: 'Autor Desconocido' },
  'feature in development': { en: 'This feature is currently in development.', it: 'Questa funzionalità è in fase di sviluppo.', es: 'Esta característica está actualmente en desarrollo.' },
  'unexpected error': { en: 'An unexpected error occurred. Please try again.', it: 'Si è verificato un errore imprevisto. Riprova.', es: 'Ocurrió un error inesperado. Por favor, inténtalo de nuevo.' },
  'fill required fields': { en: 'Please fill in all required fields.', it: 'Compila tutti i campi obbligatori.', es: 'Por favor, rellena todos los campos obligatorios.' },
  'no results found': { en: 'No results found.', it: 'Nessun risultato trovato.', es: 'No se encontraron resultados.' },
  'try different search': { en: 'Try adjusting your search or filters.', it: 'Prova a modificare la ricerca o i filtri.', es: 'Intenta ajustar tu búsqueda o filtros.' },
  'copyright notice': { en: '© 2026 IT Hub Center. All rights reserved.', it: '© 2026 IT Hub Center. Tutti i diritti riservati.', es: '© 2026 IT Hub Center. Todos los derechos reservados.' },
  'developed by': { en: 'Designed & developed by Ciro Simione', it: 'Progettato e sviluppato da Ciro Simione', es: 'Diseñado y desarrollado por Ciro Simione' },
  'select location': { en: 'Select Location', it: 'Seleziona Sede', es: 'Seleccionar Ubicación' }, 'import': { en: 'Import', it: 'Importa', es: 'Importar' },
  'export': { en: 'Export', it: 'Esporta', es: 'Exportar' },
  'import status': { en: 'Import Status', it: 'Stato Importazione', es: 'Estado de Importación' },
  'importing data': { en: 'Importing data, please wait...', it: 'Importazione dati in corso, attendere...', es: 'Importando datos, por favor espera...' },
  'import success': { en: '{count} records imported successfully.', it: '{count} record importati con successo.', es: '{count} registros importados correctamente.' },
  'import errors': { en: 'Errors encountered during import:', it: 'Errori riscontrati durante l\'importazione:', es: 'Errores encontrados durante la importación:' },
  
  // Asset Statuses
  'status in use': { en: 'In Use', it: 'In Uso', es: 'En Uso' },
  'status ready to deploy': { en: 'Ready to Deploy', it: 'Pronto all\'uso', es: 'Listo para desplegar' },
  'status pending': { en: 'Pending', it: 'In Attesa', es: 'Pendiente' },
  'status archived': { en: 'Archived', it: 'Archiviato', es: 'Archivado' },
  'status broken': { en: 'Broken', it: 'Rotto', es: 'Roto' },
  'status lost stolen': { en: 'Lost/Stolen', it: 'Perso/Rubato', es: 'Perdido/Robado' },
  'status out for diagnostics': { en: 'Out for Diagnostics', it: 'In Diagnostica', es: 'En Diagnóstico' },
  'status out for repair': { en: 'Out for Repair', it: 'In Riparazione', es: 'En Reparación' },

  // Asset Types
  'asset type pc-laptop': { en: 'PC/Laptop', it: 'PC/Laptop', es: 'PC/Portátil' },
  'asset type desktop': { en: 'Desktop', it: 'Desktop', es: 'Escritorio' },
  'asset type all-in-one': { en: 'All-in-One', it: 'All-in-One', es: 'Todo en Uno' },
  'asset type virtual machine': { en: 'Virtual Machine', it: 'Macchina Virtuale', es: 'Máquina Virtual' },
  'asset type server': { en: 'Server', it: 'Server', es: 'Servidor' },
  'asset type smartphone': { en: 'Smartphone', it: 'Smartphone', es: 'Teléfono Inteligente' },
  'asset type tablet': { en: 'Tablet', it: 'Tablet', es: 'Tableta' },
  'asset type voip phone': { en: 'VoIP Phone', it: 'Telefono VoIP', es: 'Teléfono VoIP' },
  'asset type conference phone': { en: 'Conference Phone', it: 'Telefono Conferenza', es: 'Teléfono de Conferencia' },
  'asset type monitor': { en: 'Monitor', it: 'Monitor', es: 'Monitor' },
  'asset type projector': { en: 'Projector', it: 'Proiettore', es: 'Proyector' },
  'asset type digital signage': { en: 'Digital Signage', it: 'Segnaletica Digitale', es: 'Señalización Digital' },
  'asset type printer': { en: 'Printer', it: 'Stampante', es: 'Impresora' },
  'asset type scanner': { en: 'Scanner', it: 'Scanner', es: 'Escáner' },
  'asset type copier': { en: 'Copier', it: 'Fotocopiatrice', es: 'Copiadora' },
  'asset type switch': { en: 'Switch', it: 'Switch', es: 'Conmutador' },
  'asset type router': { en: 'Router', it: 'Router', es: 'Enrutador' },
  'asset type firewall': { en: 'Firewall', it: 'Firewall', es: 'Cortafuegos' },
  'asset type access point': { en: 'Access Point', it: 'Access Point', es: 'Punto de Acceso' },
  'asset type load balancer': { en: 'Load Balancer', it: 'Bilanciatore di Carico', es: 'Balanceador de Carga' },
  'asset type pdu': { en: 'PDU', it: 'PDU', es: 'PDU' },
  'asset type ups': { en: 'UPS', it: 'UPS', es: 'SAI' },
  'asset type docking station': { en: 'Docking Station', it: 'Docking Station', es: 'Estación de Acoplamiento' },
  'asset type kvm switch': { en: 'KVM Switch', it: 'Switch KVM', es: 'Conmutador KVM' },
  'asset type webcam': { en: 'Webcam', it: 'Webcam', es: 'Cámara web' },
  'asset type peripheral': { en: 'Peripheral', it: 'Periferica', es: 'Periférico' },
  'asset type ram': { en: 'RAM', it: 'RAM', es: 'RAM' },
  'asset type other': { en: 'Other', it: 'Altro', es: 'Otro' },

  // Report Tabs & Labels
  'report tab overview': { en: 'Overview', it: 'Panoramica', es: 'Visión General' },
  'report tab financials': { en: 'Financials', it: 'Finanziario', es: 'Financiero' },
  'report tab assets': { en: 'Assets', it: 'Asset', es: 'Activos' },
  'report tab analysis': { en: 'Analysis', it: 'Analisi', es: 'Análisis' },
  'report tab users': { en: 'Users', it: 'Utenti', es: 'Usuarios' },
  'report tab audit': { en: 'Audit', it: 'Audit', es: 'Auditoría' },
  'report warranty status': { en: 'Warranty Status', it: 'Stato Garanzia', es: 'Estado de Garantía' },
  'report asset age': { en: 'Asset Age Distribution', it: 'Distribuzione Età Asset', es: 'Distribución de Edad de Activos' },
  'report expiring warranties': { en: 'Warranties Expiring Soon (90 Days)', it: 'Garanzie in Scadenza (90 Giorni)', es: 'Garantías que Caducan Pronto (90 Días)' },
  'report top locations': { en: 'Assets by Location', it: 'Asset per Posizione', es: 'Activos por Ubicación' },
  'warranty active': { en: 'Active', it: 'Attiva', es: 'Activa' },
  'warranty expired': { en: 'Expired', it: 'Scaduta', es: 'Vencida' },
  'warranty expiring': { en: 'Expiring Soon', it: 'In Scadenza', es: 'Por Vencer' },
  'warranty none': { en: 'No Warranty', it: 'Nessuna Garanzia', es: 'Sin Garantía' },
  'age <1yr': { en: '< 1 Year', it: '< 1 Anno', es: '< 1 Año' },
  'age 1-3yrs': { en: '1-3 Years', it: '1-3 Anni', es: '1-3 Años' },
  'age 3-5yrs': { en: '3-5 Years', it: '3-5 Anni', es: '3-5 Años' },
  'age >5yrs': { en: '> 5 Years', it: '> 5 Anni', es: '> 5 Años' },

  // Incident Categories
  'incident category service outage': { en: 'Service Outage', it: 'Interruzione di Servizio', es: 'Interrupción del Servicio' },
  'incident category security breach': { en: 'Security Breach', it: 'Violazione della Sicurezza', es: 'Violación de Seguridad' },
  'incident category performance degradation': { en: 'Performance Degradation', it: 'Degrado delle Prestazioni', es: 'Degradación del Rendimiento' },
  'incident category data loss': { en: 'Data Loss', it: 'Perdita di Dati', es: 'Pérdida de Datos' },
  'incident category network': { en: 'Network', it: 'Rete', es: 'Red' },
  'incident category software': { en: 'Software', it: 'Software', es: 'Software' },
  'incident category hardware': { en: 'Hardware', it: 'Hardware', es: 'Hardware' },
  'incident category password reset': { en: 'Password Reset', it: 'Reimpostazione Password', es: 'Restablecimiento de Contraseña' },
  'incident category other': { en: 'Other', it: 'Altro', es: 'Otro' },

  // Incident Status
  'incident status investigating': { en: 'Investigating', it: 'In Analisi', es: 'Investigando' },
  'incident status identified': { en: 'Identified', it: 'Identificato', es: 'Identificado' },
  'incident status monitoring': { en: 'Monitoring', it: 'Monitoraggio', es: 'Monitorizando' },
  'incident status resolved': { en: 'Resolved', it: 'Risolto', es: 'Resuelto' },

  // Login, Registration, Auth
  'sign in': { en: 'Sign In', it: 'Accedi', es: 'Iniciar Sesión' },
  'sign up': { en: 'Sign Up', it: 'Registrati', es: 'Registrarse' },
  'sign out': { en: 'Sign Out', it: 'Esci', es: 'Cerrar Sesión' },
  'logout': { en: 'Logout', it: 'Logout', es: 'Cerrar Sesión' },
  'sign in to manage ops': { en: 'Sign in to manage your IT operations.', it: 'Accedi per gestire le tue operazioni IT.', es: 'Inicia sesión para gestionar tus operaciones de TI.' },
  'create account to manage ops': { en: 'Create an account to get started.', it: 'Crea un account per iniziare.', es: 'Crea una cuenta para empezar.' },
  'email address': { en: 'Email Address', it: 'Indirizzo Email', es: 'Dirección de Correo Electrónico' },
  'password': { en: 'Password', it: 'Password', es: 'Contraseña' },
  'full name': { en: 'Full Name', it: 'Nome Completo', es: 'Nombre Completo' },
  'confirm password': { en: 'Confirm Password', it: 'Conferma Password', es: 'Confirmar Contraseña' },
  'forgot password': { en: 'Forgot password?', it: 'Password dimenticata?', es: '¿Olvidaste tu contraseña?' },
  'back to login': { en: 'Back to Login', it: 'Torna al Login', es: 'Volver a Iniciar Sesión' },
  'passwords do not match': { en: 'Passwords do not match.', it: 'Le password non corrispondono.', es: 'Las contraseñas no coinciden.' },
  'registration success title': { en: 'Registration Successful!', it: 'Registrazione Riuscita!', es: '¡Registro Exitoso!' },
  'registration success message': { en: 'A confirmation link has been sent to your email. Please check your inbox to activate your account.', it: 'Un link di conferma è stato inviato alla tua email. Controlla la tua casella di posta per attivare il tuo account.', es: 'Se ha enviado un enlace de confirmación a tu correo. Revisa tu bandeja de entrada para activar tu cuenta.' },
  'reset your password': { en: 'Reset Your Password', it: 'Reimposta la tua Password', es: 'Restablece tu Contraseña' },
  'forgot password instructions': { en: 'Enter your email address and we will send you a link to reset your your password.', it: 'Inserisci il tuo indirizzo email e ti invieremo un link per reimpostare la password.', es: 'Introduce tu dirección de correo y te enviaremos un enlace para restablecer tu contraseña.' },
  'send reset link': { en: 'Send Reset Link', it: 'Invia Link di Reset', es: 'Enviar Enlace de Restablecimiento' },
  'reset link sent title': { en: 'Reset Link Sent', it: 'Link di Reset Inviato', es: 'Enlace de Restablecimiento Enviado' },
  'reset link sent message': { en: 'If an account with that email exists, a password reset link has been sent.', it: 'Se esiste un account con quella email, è stato inviato un link per il reset della password.', es: 'Si existe una cuenta con ese correo, se ha enviado un enlace para restablecer la contraseña.' },
  'update your password': { en: 'Update Your Password', it: 'Aggiorna la tua Password', es: 'Actualiza tu Contraseña' },
  'update password': { en: 'Update Password', it: 'Aggiorna Password', es: 'Actualizar Contraseña' },
  'password updated successfully': { en: 'Your password has been updated successfully.', it: 'La tua password è stata aggiornata con successo.', es: 'Tu contraseña ha sido actualizada correctamente.' },
  'password update success': { en: 'Password updated successfully!', it: 'Password aggiornata con successo!', es: '¡Contraseña actualizada correctamente!' },
  'password update failed generic': { en: 'Failed to update password. Please try again.', it: 'Aggiornamento password fallito. Riprova.', es: 'No se pudo actualizar la contraseña. Inténtalo de nuevo.' },
  'current password incorrect': { en: 'Your current password is not correct.', it: 'La tua password attuale non è corretta.', es: 'Tu contraseña actual no es correcta.' },
  'password too short': { en: 'New password must be at least 8 characters long.', it: 'La nuova password deve essere lunga almeno 8 caratteri.', es: 'La nueva contraseña debe tener al menos 8 caracteres.' },
  'proceed to login': { en: 'Proceed to Login', it: 'Vai al Login', es: 'Proceder a Iniciar Sesión' },
  'update password wait session': { en: 'Please wait, verifying your session...', it: 'Attendere, verifica della sessione in corso...', es: 'Por favor espera, verificando tu sesión...' },
  'new password': { en: 'New Password', it: 'Nuova Password', es: 'Nueva Contraseña' },
  'confirm new password': { en: 'Confirm New Password', it: 'Conferma Nuova Password', es: 'Confirmar Nueva Contraseña' },
  
  // Change Password
  'change password': { en: 'Change Password', it: 'Cambia Password', es: 'Cambiar Contraseña' },
  'current password': { en: 'Current Password', it: 'Password Attuale', es: 'Contraseña Actual' },
  'ai password prompt': { en: 'Analyze the strength of this password and give a short tip:', it: 'Analizza la forza di questa password e dai un breve consiglio:', es: 'Analiza la fortaleza de esta contraseña y da un breve consejo:' },
  'ai thinking': { en: 'AI is thinking...', it: 'L\'IA sta pensando...', es: 'La IA está pensando...' },
  'ai password strength': { en: 'Strength:', it: 'Forza:', es: 'Fortaleza:' },
  'ai strength good': { en: 'Good', it: 'Buona', es: 'Buena' },
  'ai strength medium': { en: 'Medium', it: 'Media', es: 'Media' },
  'ai strength poor': { en: 'Poor', it: 'Debole', es: 'Débil' },
  'ai tip': { en: 'Tip:', it: 'Consiglio:', es: 'Consejo:' },

  // Auth Errors
  'invalid credentials': { en: 'Invalid email or password. If you recently signed up, we have re-sent your confirmation email.', it: 'Email o password non validi. Se ti sei registrato di recente, ti abbiamo inviato nuovamente l\'email di conferma.', es: 'Correo o contraseña inválidos. Si te registraste recientemente, te hemos reenviado el correo de confirmación.' },
  'email not confirmed': { en: 'Please confirm your email address first.', it: 'Per favore, conferma prima il tuo indirizzo email.', es: 'Por favor, confirma tu dirección de correo primero.' },
  'login failed': { en: 'Login failed. Please try again.', it: 'Accesso fallito. Riprova.', es: 'Inicio de sesión fallido. Por favor, inténtalo de nuevo.' },
  'profile fetch failed': { en: 'Failed to fetch user profile. Please contact support.', it: 'Impossibile recuperare il profilo utente. Contatta il supporto.', es: 'No se pudo obtener el perfil de usuario. Contacta a soporte.' },
  'email already exists': { en: 'An account with this email already exists.', it: 'Esiste già un account con questa email.', es: 'Ya existe una cuenta con este correo.' },
  'registration failed': { en: 'Registration failed. Please try again.', it: 'Registrazione fallita. Riprova.', es: 'Registro fallido. Por favor, inténtalo de nuevo.' },
  'password update failed': { en: 'Failed to update password. The link may be expired.', it: 'Aggiornamento password fallito. Il link potrebbe essere scaduto.', es: 'No se pudo actualizar la contraseña. El enlace puede haber expirado.' },
  
  // 2FA Auth
  '2fa verification code': { en: '2FA Verification Code', it: 'Codice di Verifica 2FA', es: 'Código de Verificación 2FA' },
  'verify code': { en: 'Verify Code', it: 'Verifica Codice', es: 'Verificar Código' },
  'invalid 2fa code': { en: 'Invalid 2FA code. Please try again.', it: 'Codice 2FA non valido. Riprova.', es: 'Código 2FA inválido. Inténtalo de nuevo.' },
  'two factor authentication': { en: 'Two-Factor Authentication', it: 'Autenticazione a Due Fattori', es: 'Autenticación de Dos Factores' },
  '2fa status enabled': { en: 'Two-factor authentication is currently enabled.', it: 'L\'autenticazione a due fattori è attualmente abilitata.', es: 'La autenticación de dos factores está habilitada actualmente.' },
  '2fa status disabled': { en: 'Two-factor authentication is not enabled.', it: 'L\'autenticazione a due fattori non è abilitata.', es: 'La autenticación de dos factores no está habilitada.' },
  'disable 2fa': { en: 'Disable 2FA', it: 'Disabilita 2FA', es: 'Deshabilitar 2FA' },
  'enable 2fa': { en: 'Enable 2FA', it: 'Abilita 2FA', es: 'Habilitar 2FA' },
  '2fa setup title': { en: 'Setup Two-Factor Authentication', it: 'Configura Autenticazione a Due Fattori', es: 'Configurar Autenticación de Dos Factores' },
  '2fa setup step1': { en: 'Scan the QR code below with your authenticator app (Google Authenticator, Authy, etc.).', it: 'Scansiona il codice QR qui sotto con la tua app di autenticazione (Google Authenticator, Authy, ecc.).', es: 'Escanea el código QR a continuación con tu aplicación de autenticación (Google Authenticator, Authy, etc.).' },
  'or enter secret': { en: 'Or enter this secret manually:', it: 'Oppure inserisci questo segreto manualmente:', es: 'O introduce este secreto manualmente:' },
  '2fa setup step2': { en: 'Enter the 6-digit code from your app to verify.', it: 'Inserisci il codice a 6 cifre dalla tua app per verificare.', es: 'Introduce el código de 6 dígitos de tu aplicación para verificar.' },
  'verification code': { en: 'Verification Code', it: 'Codice di Verifica', es: 'Código de Verificación' },
  'verify and enable': { en: 'Verify & Enable', it: 'Verifica e Abilita', es: 'Verificar y Habilitar' },
  '2fa disabled successfully': { en: 'Two-factor authentication disabled.', it: 'Autenticazione a due fattori disabilitata.', es: 'Autenticación de dos factores deshabilitada.' },

  // Page Titles & Sidebar
  'page title dashboard': { en: 'Dashboard', it: 'Dashboard', es: 'Panel de Control' },
  'page title tickets': { en: 'Tickets', it: 'Ticket', es: 'Tickets' },
  'page title assets': { en: 'Assets', it: 'Asset', es: 'Activos' },
  'page title licenses': { en: 'Licenses', it: 'Licenze', es: 'Licencias' },
  'page title incidents': { en: 'Incident Log', it: 'Registro Incidenti', es: 'Registro de Incidentes' },
  'page title session': { en: 'Session', it: 'Sessione', es: 'Sesión' },
  'page title reports': { en: 'Reports', it: 'Report', es: 'Informes' },
  'page title kb': { en: 'Knowledge Base', it: 'Knowledge Base', es: 'Base de Conocimiento' },
  'page title settings': { en: 'Settings', it: 'Impostazioni', es: 'Configuración' },
  'page title policies': { en: 'Policies', it: 'Policy', es: 'Políticas' },
  'dashboard': { en: 'Dashboard', it: 'Dashboard', es: 'Panel de Control' },
  'tickets': { en: 'Tickets', it: 'Ticket', es: 'Tickets' },
  'assets': { en: 'Assets', it: 'Asset', es: 'Activos' },
  'licenses': { en: 'Licenses', it: 'Licenze', es: 'Licencias' },
  'incidents': { en: 'Incidents', it: 'Incidenti', es: 'Incidentes' },
  'session': { en: 'Session', it: 'Sessione', es: 'Sesión' },
  'reports': { en: 'Reports', it: 'Report', es: 'Informes' },
  'kb': { en: 'Knowledge Base', it: 'Knowledge Base', es: 'Base de Conocimiento' },
  'settings': { en: 'Settings', it: 'Impostazioni', es: 'Configuración' },

  // Settings Submenu
  'settings profile': { en: 'Profile', it: 'Profilo', es: 'Perfil' },
  'settings security': { en: 'Security', it: 'Sicurezza', es: 'Seguridad' },
  'settings users': { en: 'Users', it: 'Utenti', es: 'Usuarios' },
  'settings integrations': { en: 'Integrations', it: 'Integrazioni', es: 'Integraciones' },
  'settings backup': { en: 'Backup & Restore', it: 'Backup & Ripristino', es: 'Copia de Seguridad y Restauración' },
  'policies': { en: 'Policies', it: 'Policy', es: 'Políticas' },
  'sla policies': { en: 'SLA Policies', it: 'Policy SLA', es: 'Políticas de SLA' },
  'settings application': { en: 'Application', it: 'Applicazione', es: 'Aplicación' },
  'settings profile desc': { en: 'Manage your personal information and preferences.', it: 'Gestisci le tue informazioni personali e preferenze.', es: 'Gestiona tu información personal y preferencias.' },
  'settings security desc': { en: 'Update your password and manage two-factor authentication.', it: 'Aggiorna la tua password e gestisci l\'autenticazione a due fattori.', es: 'Actualiza tu contraseña y gestiona la autenticación de dos factores.' },
  'settings users desc': { en: 'Manage users, roles, and permissions.', it: 'Gestisci utenti, ruoli e permessi.', es: 'Gestiona usuarios, roles y permisos.' },
  'settings integrations desc': { en: 'Connect with third-party applications.', it: 'Connettiti con applicazioni di terze parti.', es: 'Conecta con aplicaciones de terceros.' },
  'settings policies desc': { en: 'View company-wide policies for assets and security.', it: 'Visualizza le policy aziendali per asset e sicurezza.', es: 'Ver las políticas de toda la empresa para activos y seguridad.' },
  'settings application desc': { en: 'Manage PWA installation and application settings.', it: 'Gestisci l\'installazione PWA e le impostazioni dell\'applicazione.', es: 'Gestiona la instalación de la PWA y la configuración de la aplicación.' },
  'settings backup desc': { en: 'Export and import your data.', it: 'Esporta e importa i tuoi dati.', es: 'Exporta e importa tus datos.' },
  'settings language': { en: 'Language', it: 'Lingua', es: 'Idioma' },
  'settings language desc': { en: 'Choose your preferred language.', it: 'Scegli la tua lingua preferita.', es: 'Elige tu idioma preferido.' },
  'choose how the app looks': { en: 'Choose how the app looks to you.', it: 'Scegli come appare l\'app per te.', es: 'Elige cómo se ve la aplicación para ti.' },
  'light mode': { en: 'Light', it: 'Chiaro', es: 'Claro' },
  'dark mode': { en: 'Dark', it: 'Scuro', es: 'Oscuro' },
  'system preference': { en: 'System', it: 'Sistema', es: 'Sistema' },
  'appearance': { en: 'Appearance', it: 'Aspetto', es: 'Apariencia' },
  'theme': { en: 'Theme', it: 'Tema', es: 'Tema' },
  'settings notifications': { en: 'Notifications', it: 'Notifiche', es: 'Notificaciones' },
  'settings notifications desc': { en: 'Manage your notification preferences.', it: 'Gestisci le tue preferenze di notifica.', es: 'Gestiona tus preferencias de notificaciones.' },
  'notification email': { en: 'Email Notifications', it: 'Notifiche Email', es: 'Notificaciones por Correo' },
  'notification in app': { en: 'In-App Notifications', it: 'Notifiche In-App', es: 'Notificaciones en la Aplicación' },
  'notification ticket updates': { en: 'Ticket Updates', it: 'Aggiornamenti Ticket', es: 'Actualizaciones de Tickets' },
  'notification sla warnings': { en: 'SLA Warnings', it: 'Avvisi SLA', es: 'Advertencias de SLA' },
  'mute notifications': { en: 'Mute Notifications', it: 'Silenzia Notifiche', es: 'Silenciar Notificaciones' },
  'mute notifications description': { en: 'Temporarily pause notifications.', it: 'Metti temporaneamente in pausa le notifiche.', es: 'Pausar temporalmente las notificaciones.' },
  'notifications muted until': { en: 'Notifications muted until {time}', it: 'Notifiche silenziate fino alle {time}', es: 'Notificaciones silenciadas hasta las {time}' },
  'unmute': { en: 'Unmute', it: 'Riattiva', es: 'Reactivar' },
  'select mute duration': { en: 'Select duration...', it: 'Seleziona durata...', es: 'Seleccionar duración...' },
  'mute for 30 mins': { en: '30 Minutes', it: '30 Minuti', es: '30 Minutos' },
  'mute for 1 hour': { en: '1 Hour', it: '1 Ora', es: '1 Hora' },
  'mute for 4 hours': { en: '4 Hours', it: '4 Ore', es: '4 Horas' },
  'mute until tomorrow': { en: 'Until Tomorrow', it: 'Fino a Domani', es: 'Hasta Mañana' },
  'mute custom': { en: 'Custom...', it: 'Personalizzato...', es: 'Personalizado...' },
  'settings recurring mute title': { en: 'Recurring Quiet Hours', it: 'Ore di Quiete Ricorrenti', es: 'Horas de Silencio Recurrentes' },
  'settings recurring mute desc': { en: 'Automatically mute notifications during specific times.', it: 'Silenzia automaticamente le notifiche in orari specifici.', es: 'Silenciar automáticamente las notificaciones en horarios específicos.' },
  'settings mute weekends': { en: 'Mute on Weekends', it: 'Silenzia nei Weekend', es: 'Silenciar los Fines de Semana' },
  'settings mute outside hours': { en: 'Mute Outside Work Hours', it: 'Silenzia Fuori Orario di Lavoro', es: 'Silenciar Fuera del Horario Laboral' },
  'settings quiet hours from': { en: 'From', it: 'Dalle', es: 'Desde' },
  'settings quiet hours to': { en: 'To', it: 'Alle', es: 'Hasta' },
  'settings sla exception': { en: 'Note: Critical SLA alerts will always bypass mute settings.', it: 'Nota: Gli avvisi SLA critici ignoreranno sempre le impostazioni di silenzio.', es: 'Nota: Las alertas críticas de SLA sempre ignorarán la configuración de silencio.' },
  'settings saved successfully': { en: 'Settings saved successfully.', it: 'Impostazioni salvate con successo.', es: 'Configuración guardada correctamente.' },
  'time date format': { en: 'Time & Date Format', it: 'Formato Data e Ora', es: 'Formato de Fecha y Hora' },
  'week start': { en: 'Week Starts On', it: 'La settimana inizia di', es: 'La semana comienza el' },
  'week start sunday': { en: 'Sunday', it: 'Domenica', es: 'Domingo' },
  'week start monday': { en: 'Monday', it: 'Lunedì', es: 'Lunes' },
  'time format': { en: 'Time Format', it: 'Formato Ora', es: 'Formato de Hora' },
  'time format 24h': { en: '24 Hours (13:00)', it: '24 Ore (13:00)', es: '24 Horas (13:00)' },
  'time format 12h': { en: '12 Hours (1:00 PM)', it: '12 Ore (1:00 PM)', es: '12 Horas (1:00 PM)' },
  'date format': { en: 'Date Format', it: 'Formato Data', es: 'Formato de Fecha' },
  'date format mmddyyyy': { en: 'MM/DD/YYYY', it: 'MM/GG/AAAA', es: 'MM/DD/AAAA' },
  'date format ddmmyyyy': { en: 'DD/MM/YYYY', it: 'GG/MM/AAAA', es: 'DD/MM/AAAA' },
  'date format yyyymmdd': { en: 'YYYY/MM/DD', it: 'AAAA/MM/GG', es: 'AAAA/MM/DD' },
  'email signature': { en: 'Email Signature', it: 'Firma Email', es: 'Firma de Correo' },
  'signature text': { en: 'Signature Text', it: 'Testo della Firma', es: 'Texto de la Firma' },
  'upload logo': { en: 'Upload Logo', it: 'Carica Logo', es: 'Subir Logotipo' },
  'change': { en: 'Change', it: 'Cambia', es: 'Cambiar' },
  'remove': { en: 'Remove', it: 'Rimuovi', es: 'Eliminar' },
  'signature preview': { en: 'Signature Preview', it: 'Anteprima Firma', es: 'Vista Previa de la Firma' },
  'save signature': { en: 'Save Signature', it: 'Salva Firma', es: 'Guardar Firma' },
  'signature saved successfully': { en: 'Signature saved successfully.', it: 'Firma salvata con successo.', es: 'Firma guardada correctamente.' },
  'update avatar': { en: 'Update Avatar', it: 'Aggiorna Avatar', es: 'Actualizar Avatar' },
  'tab select preset': { en: 'Preset', it: 'Predefinito', es: 'Preestablecido' },
  'tab upload file': { en: 'Upload', it: 'Carica', es: 'Subir' },
  'tab from url': { en: 'URL', it: 'URL', es: 'URL' },
  'preview': { en: 'Preview', it: 'Anteprima', es: 'Vista Previa' },
  'image url placeholder': { en: 'https://example.com/image.png', it: 'https://esempio.com/immagine.png', es: 'https://ejemplo.com/imagen.png' },
  'save avatar': { en: 'Save Avatar', it: 'Salva Avatar', es: 'Guardar Avatar' },
  'upload failed': { en: 'Upload failed. Please try again.', it: 'Caricamento fallito. Riprova.', es: 'Error al subir. Inténtalo de nuevo.' },
  'no status set': { en: 'No status set.', it: 'Nessuno stato impostato.', es: 'Sin estado establecido.' },
  'whats on your mind': { en: "What's on your mind?", it: "A cosa stai pensando?", es: "¿En qué estás pensando?" },
  'clear': { en: 'Clear', it: 'Cancella', es: 'Borrar' },
  'set status': { en: 'Set Status', it: 'Imposta Stato', es: 'Establecer Estado' },

  // Users Settings
  'import users': { en: 'Import Users', it: 'Importa Utenti', es: 'Importar Usuarios' },
  'new user': { en: 'New User', it: 'Nuovo Utente', es: 'Nuevo Usuario' },
  'user search placeholder': { en: 'Search users...', it: 'Cerca utenti...', es: 'Buscar usuarios...' },
  'user': { en: 'User', it: 'Utente', es: 'Usuario' },
  'user role': { en: 'Role', it: 'Ruolo', es: 'Rol' },
  'company': { en: 'Company', it: 'Azienda', es: 'Empresa' },
  'last login': { en: 'Last Login', it: 'Ultimo Accesso', es: 'Último Acceso' },
  'edit user': { en: 'Edit User', it: 'Modifica Utente', es: 'Editar Usuario' },
  'invite user': { en: 'Invite User', it: 'Invita Utente', es: 'Invitar Usuario' },
  'invite user desc': { en: 'Send an invitation email to a new user.', it: 'Invia un\'email di invito a un nuovo utente.', es: 'Enviar un correo de invitación a un nuevo usuario.' },
  'cannot change own role': { en: 'You cannot change your own role.', it: 'Non puoi cambiare il tuo ruolo.', es: 'No puedes cambiar tu propio rol.' },
  'invite': { en: 'Invite', it: 'Invita', es: 'Invitar' },
  'user import instructions': { en: 'Upload a CSV file with the following columns:', it: 'Carica un file CSV con le seguenti colonne:', es: 'Sube un archivo CSV con las siguientes columnas:' },
  'user import desc': { en: 'The email field is required. Role must be one of: Admin, Agent, Member, End User.', it: 'Il campo email è obbligatorio. Il ruolo deve essere uno tra: Admin, Agent, Member, End User.', es: 'El campo de correo es obligatorio. El rol debe ser uno de: Admin, Agent, Member, End User.' },
  'select csv file': { en: 'Select CSV File', it: 'Seleziona File CSV', es: 'Seleccionar Archivo CSV' },

  // Integration Settings
  'integration search placeholder': { en: 'Search integrations...', it: 'Cerca integrazioni...', es: 'Buscar integraciones...' },
  'manage': { en: 'Manage', it: 'Gestisci', es: 'Gestionar' },
  'connect': { en: 'Connect', it: 'Connetti', es: 'Conectar' },
  'cant find integration': { en: "Can't find what you're looking for?", it: "Non trovi quello che cerchi?", es: "¿No encuentras lo que buscas?" },
  'suggest one': { en: 'Suggest a new integration', it: 'Suggerisci una nuova integrazione', es: 'Sugerir una nueva integración' },
  'manage connection to': { en: 'Manage connection to {service}', it: 'Gestisci connessione a {service}', es: 'Gestionar conexión con {service}' },
  'api key': { en: 'API Key', it: 'Chiave API', es: 'Clave API' },
  'enter api key': { en: 'Enter {service} API Key', it: 'Inserisci Chiave API {service}', es: 'Introducir Clave API de {service}' },
  'disconnect': { en: 'Disconnect', it: 'Disconnetti', es: 'Desconectar' },
  'confirm disconnect': { en: 'Are you sure you want to disconnect {service}? This may break existing workflows.', it: 'Sei sicuro di voler disconnettere {service}? Questo potrebbe interrompere i flussi di lavoro esistenti.', es: '¿Estás seguro de que quieres desconectar {service}? Esto podría romper los flujos de trabajo existentes.' },
  'suggest integration title': { en: 'Suggest Integration', it: 'Suggerisci Integrazione', es: 'Sugerir Integración' },
  'suggestion thanks': { en: 'Thanks for your suggestion! We will consider it for future updates.', it: 'Grazie per il tuo suggerimento! Lo prenderemo in considerazione per i futuri aggiornamenti.', es: '¡Gracias por tu sugerencia! Lo consideraremos para futuras actualizaciones.' },
  'integration name': { en: 'Integration Name', it: 'Nome Integrazione', es: 'Nombre de la Integración' },
  'integration reason': { en: 'How would you use this integration?', it: 'Come useresti questa integrazione?', es: '¿Cómo usarías esta integración?' },
  'failed to submit suggestion': { en: 'Failed to submit suggestion.', it: 'Invio suggerimento fallito.', es: 'Error al enviar la sugerencia.' },
  'submit suggestion': { en: 'Submit Suggestion', it: 'Invia Suggerimento', es: 'Enviar Sugerencia' },
  'integration slack desc': { en: 'Connect Slack to receive ticket notifications and updates.', it: 'Connetti Slack per ricevere notifiche e aggiornamenti sui ticket.', es: 'Conecta Slack para recibir notificaciones y actualizaciones de tickets.' },
  'integration jira desc': { en: 'Sync tickets with Jira issues for engineering tracking.', it: 'Sincronizza i ticket con i problemi Jira per il tracciamento tecnico.', es: 'Sincroniza tickets con problemas de Jira para el seguimiento de ingeniería.' },
  'integration github desc': { en: 'Link tickets to GitHub issues and pull requests.', it: 'Collega i ticket a problemi e pull request di GitHub.', es: 'Vincula tickets a problemas y solicitudes de extracción de GitHub.' },
  'integration datadog desc': { en: 'Create incidents automatically from Datadog alerts.', it: 'Crea incidenti automaticamente dagli avvisi Datadog.', es: 'Crea incidentes automáticamente desde alertas de Datadog.' },
  'integration zendesk desc': { en: 'Import tickets from Zendesk.', it: 'Importa ticket da Zendesk.', es: 'Importar tickets desde Zendesk.' },
  'integration zapier desc': { en: 'Connect IT Hub with 5000+ apps via Zapier.', it: 'Connetti IT Hub con 5000+ app tramite Zapier.', es: 'Conecta IT Hub con 5000+ aplicaciones a través de Zapier.' },
  'integration msteams desc': { en: 'Receive notifications in Microsoft Teams channels.', it: 'Ricevi notifiche nei canali Microsoft Teams.', es: 'Recibe notificaciones en canales de Microsoft Teams.' },
  'integration pagerduty desc': { en: 'Trigger PagerDuty incidents from critical tickets.', it: 'Attiva incidenti PagerDuty da ticket critici.', es: 'Activa incidentes de PagerDuty desde tickets críticos.' },
  'integration okta desc': { en: 'Sync users and groups from Okta.', it: 'Sincronizza utenti e gruppi da Okta.', es: 'Sincroniza usuarios y grupos desde Okta.' },
  'integration onepassword desc': { en: 'Securely manage shared credentials.', it: 'Gestisci in modo sicuro le credenziali condivise.', es: 'Gestiona de forma segura las credenciales compartidas.' },
  'integration salesforce desc': { en: 'View CRM data alongside tickets.', it: 'Visualizza i dati CRM insieme ai ticket.', es: 'Ver datos de CRM junto con los tickets.' },
  'integration clickup desc': { en: 'Create ClickUp tasks from tickets.', it: 'Crea attività ClickUp dai ticket.', es: 'Crear tareas de ClickUp desde tickets.' },
  'integration telegram desc': { en: 'Receive bot notifications via Telegram.', it: 'Ricevi notifiche bot tramite Telegram.', es: 'Recibe notificaciones de bot a través de Telegram.' },
  'integration whatsapp desc': { en: 'Send status updates via WhatsApp.', it: 'Invia aggiornamenti di stato tramite WhatsApp.', es: 'Enviar actualizaciones de estado a través de WhatsApp.' },

  // Application Settings
  'app is installed': { en: 'Application is installed.', it: 'L\'applicazione è installata.', es: 'La aplicación está instalada.' },
  'install app': { en: 'Install App', it: 'Installa App', es: 'Instalar Aplicación' },
  'install not supported': { en: 'Installation is not supported on this browser or device.', it: 'L\'installazione non è supportata su questo browser o dispositivo.', es: 'La instalación no es compatible con questo browser o dispositivo.' },

  // Policy Settings
  'asset policies title': { en: 'Asset Management Policies', it: 'Policy di Gestione Asset', es: 'Políticas de Gestión de Activos' },
  'asset policies desc admin': { en: 'Can create, edit, delete, and reassign all assets.', it: 'Possono creare, modificare, eliminare e riassegnare tutti gli asset.', es: 'Pueden crear, editar, eliminar y reasignar todos los activos.' },
  'asset policies desc user': { en: 'Can view assets assigned to them.', it: 'Possono visualizzare gli asset a loro assegnati.', es: 'Pueden ver los activos que se les han asignado.' },
  'geolocation policies title': { en: 'Geolocation Policies', it: 'Policy di Geolocalizzazione', es: 'Políticas de Geolocalización' },
  'enable geofencing': { en: 'Enable Geofencing (Coming Soon)', it: 'Abilita Geofencing (Prossimamente)', es: 'Habilitar Geofencing (Próximamente)' },
  'geofencing desc': { en: 'Restrict access and track assets based on geographic location.', it: 'Limita l\'accesso e traccia gli asset in base alla posizione geografica.', es: 'Restringir el acceso y rastrear activos según la ubicación geográfica.' },

  // Roles
  'role admin': { en: 'Admin', it: 'Admin', es: 'Admin' },
  'role agent': { en: 'Agent', it: 'Agente', es: 'Agente' },
  'role member': { en: 'Member', it: 'Membro', es: 'Miembro' },
  'role end user': { en: 'End User', it: 'Utente Finale', es: 'Usuario Final' },
  'role_admin': { en: 'Admin', it: 'Admin', es: 'Admin' },
  'role_agent': { en: 'Agent', it: 'Agente', es: 'Agente' },
  'role_member': { en: 'Member', it: 'Membro', es: 'Miembro' },
  'role_end-user': { en: 'End User', it: 'Utente Finale', es: 'Usuario Final' },

  // Sidebar & Header
  'expand sidebar': { en: 'Expand sidebar', it: 'Espandi barra laterale', es: 'Expandir barra lateral' },
  'collapse sidebar': { en: 'Collapse sidebar', it: 'Comprimi barra laterale', es: 'Contraer barra lateral' },
  'search or jump to': { en: 'Search or jump to...', it: 'Cerca o vai a...', es: 'Buscar o ir a...' },
  'set status title': { en: 'Set Status', it: 'Imposta Stato', es: 'Establecer Estado' },
  'switch to light mode': { en: 'Switch to light mode', it: 'Passa a tema chiaro', es: 'Cambiar a modo claro' },
  'switch to dark mode': { en: 'Switch to dark mode', it: 'Passa a tema scuro', es: 'Cambiar a modo oscuro' },
  
  // Command Palette
  'type a command': { en: 'Type a command or search...', it: 'Scrivi un comando o cerca...', es: 'Escribe un comando o busca...' },
  'cmd go to dashboard': { en: 'Go to Dashboard', it: 'Vai alla Dashboard', es: 'Ir al Panel de Control' },
  'cmd go to tickets': { en: 'Go to Tickets', it: 'Vai ai Ticket', es: 'Ir a Tickets' },
  'cmd go to assets': { en: 'Go to Assets', it: 'Vai agli Asset', es: 'Ir a Activos' },
  'cmd go to licenses': { en: 'Go to Licenses', it: 'Vai alle Licenze', es: 'Ir a Licencias' },
  'cmd go to incidents': { en: 'Go to Incidents', it: 'Vai agli Incidenti', es: 'Ir a Incidentes' },
  'cmd go to kb': { en: 'Go to Knowledge Base', it: 'Vai alla Knowledge Base', es: 'Ir a Base de Conocimiento' },
  'cmd go to reports': { en: 'Go to Reports', it: 'Vai ai Report', es: 'Ir a Informes' },
  'cmd go to settings': { en: 'Go to Settings', it: 'Vai alle Impostazioni', es: 'Ir a Configuración' },
  'cmd create new ticket': { en: 'Create New Ticket', it: 'Crea Nuovo Ticket', es: 'Crear Nuevo Ticket' },
  'cmd toggle theme': { en: 'Toggle Theme', it: 'Cambia Tema', es: 'Cambiar Tema' },
  'cmd logout': { en: 'Logout', it: 'Esci', es: 'Cerrar Sesión' },

  // Languages
  'language': { en: 'Language', it: 'Lingua', es: 'Idioma' },
  'lang en': { en: 'EN', it: 'EN', es: 'EN' },
  'lang it': { en: 'IT', it: 'IT', es: 'IT' },
  'lang es': { en: 'ES', it: 'ES', es: 'ES' },
  
  // Notifications
  'notifications': { en: 'Notifications', it: 'Notifiche', es: 'Notificaciones' },
  'mark all as read': { en: 'Mark all as read', it: 'Segna tutte come lette', es: 'Marcar tutte come lette' },
  'no notifications': { en: 'No new notifications.', it: 'Nessuna nuova notifica.', es: 'No hay notificaciones nuevas.' },
  'notification_ticket_sla_urgent': { en: 'SLA Breach: Ticket #{id} "{subject}" is overdue!', it: 'Violazione SLA: Il ticket #{id} "{subject}" è in ritardo!', es: 'Incumplimiento de SLA: ¡El ticket #{id} "{subject}" está vencido!' },
  'notification_ticket_sla_high': { en: 'SLA Warning: Ticket #{id} "{subject}" is approaching breach.', it: 'Avviso SLA: Il ticket #{id} "{subject}" si sta avvicinando alla scadenza.', es: 'Advertencia de SLA: El ticket #{id} "{subject}" se acerca al vencimiento.' },
  'notification_unassigned_urgent': { en: 'Urgent Ticket #{id} "{subject}" is unassigned!', it: 'Il ticket urgente #{id} "{subject}" non è assegnato!', es: '¡El ticket urgente #{id} "{subject}" no está asignado!' },
  'notification_unassigned_high': { en: 'High Priority Ticket #{id} "{subject}" needs assignment.', it: 'Il ticket ad alta priorità #{id} "{subject}" necessita di assegnazione.', es: 'El ticket de alta prioridad #{id} "{subject}" necesita asignación.' },
  'notification_asset_warranty': { en: 'Warranty for {name} expires in {days} days.', it: 'La garanzia per {name} scade tra {days} giorni.', es: 'La garantía de {name} expira en {days} días.' },
  'notification_license_expiry': { en: 'License {name} expires in {days} days.', it: 'La licenza {name} scade tra {days} giorni.', es: 'La licencia {name} expira en {days} días.' },
  
  // Dashboard
  'greeting user': { en: 'Good morning, {name}!', it: 'Buongiorno, {name}!', es: '¡Buenos días, {name}!' },
  'user dashboard subtitle': { en: 'Here is an overview of your activity.', it: 'Ecco una panoramica della tua attività.', es: 'Aquí tienes un resumen de tu actividad.' },
  'status summary': { en: 'Status Summary', it: 'Riepilogo Stato', es: 'Resumen de Estado' },
  'your recent tickets': { en: 'Your Recent Tickets', it: 'I tuoi Ticket Recenti', es: 'Tus Tickets Recientes' },
  'view all tickets': { en: 'View All Tickets', it: 'Vedi tutti i Ticket', es: 'Ver todos los Tickets' },
  'all caught up': { en: 'All caught up!', it: 'Tutto aggiornato!', es: '¡Todo al día!' },
  'no tickets prompt': { en: 'You have no open tickets at this time.', it: 'Non hai ticket aperti in questo momento.', es: 'Non hai ticket aperti in questo momento.' },
  'sla status': { en: 'SLA Status', it: 'Stato SLA', es: 'Estado de SLA' },
  'quick actions': { en: 'Quick Actions', it: 'Azioni Rapide', es: 'Acciones Rápidas' },
  'new ticket': { en: 'New Ticket', it: 'Nuovo Ticket', es: 'Nuevo Ticket' },
  'new asset': { en: 'New Asset', it: 'Nuovo Asset', es: 'Nuevo Activo' },
  'new incident': { en: 'New Incident', it: 'Nuovo Incidente', es: 'Nuevo Incidente' },
  'tickets by status': { en: 'Tickets by Status', it: 'Ticket per Stato', es: 'Tickets por Estado' },
  'incidents by category': { en: 'Incidents by Category', it: 'Incidenti per Categoria', es: 'Incidentes por Categoría' },
  'my assigned tickets': { en: 'My Assigned Tickets', it: 'I miei Ticket Assegnati', es: 'Mis Tickets Asignados' },
  'requester': { en: 'Requester', it: 'Richiedente', es: 'Solicitante' },
  'licenses nearing capacity': { en: 'Licenses Nearing Capacity', it: 'Licenze in Esaurimento', es: 'Licencias a punto de Agotarse' },
  'no low licenses': { en: 'No licenses are nearing their capacity.', it: 'Nessuna licenza si sta avvicinando alla capacità massima.', es: 'Ninguna licencia está cerca de su capacità.' },
  'recent incidents': { en: 'Recent Incidents', it: 'Incidenti Recenti', es: 'Incidentes Recientes' },
  'no active incidents': { en: 'No active incidents to display.', it: 'Nessun incidente attivo da visualizzare.', es: 'No hay incidentes activos para mostrar.' },
  'unassigned': { en: 'Unassigned', it: 'Non Assegnato', es: 'Sin Asignar' },
  'customize': { en: 'Customize', it: 'Personalizza', es: 'Personalizar' },
  'customize dashboard': { en: 'Customize Dashboard', it: 'Personalizza Dashboard', es: 'Personalizar Panel' },

  // Tickets
  'ticket id': { en: 'Ticket ID', it: 'ID Ticket', es: 'ID de Ticket' },
  'subject': { en: 'Subject', it: 'Oggetto', es: 'Asunto' },
  'status': { en: 'Status', it: 'Stato', es: 'Estado' },
  'priority': { en: 'Priority', it: 'Priorità', es: 'Prioridad' },
  'assignee': { en: 'Assignee', it: 'Assegnatario', es: 'Asignado' },
  'sla due': { en: 'SLA Due', it: 'Scadenza SLA', es: 'Vencimiento SLA' },
  'updated at': { en: 'Last Updated', it: 'Ultimo Aggiornamento', es: 'Última Actualización' },
  'create new ticket': { en: 'Create New Ticket', it: 'Crea Nuovo Ticket', es: 'Crear Nuevo Ticket' },
  'all tickets': { en: 'All Tickets', it: 'Tutti i Ticket', es: 'Todos los Tickets' },
  'my tickets': { en: 'My Tickets', it: 'I Miei Ticket', es: 'Mis Tickets' },
  'ticket search placeholder': { en: 'Search by ID, subject, or requester...', it: 'Cerca per ID, oggetto o richiedente...', es: 'Buscar por ID, asunto o solicitante...' },
  'no tickets found filter': { en: 'No tickets match the current filters.', it: 'Nessun ticket corrisponde ai filtri attuali.', es: 'Ningún ticket coincide con los filtros actuales.' },
  'ticket status open': { en: 'Open', it: 'Aperto', es: 'Abierto' },
  'ticket status in progress': { en: 'In Progress', it: 'In Corso', es: 'En Progreso' },
  'ticket status resolved': { en: 'Resolved', it: 'Risolto', es: 'Resuelto' },
  'ticket status closed': { en: 'Closed', it: 'Chiuso', es: 'Cerrado' },
  'switch to board view': { en: 'Board View', it: 'Vista Board', es: 'Vista Tablero' },
  'switch to list view': { en: 'List View', it: 'Vista Elenco', es: 'Vista Lista' },
  'generate ai reply': { en: 'AI Reply', it: 'Risposta IA', es: 'Respuesta IA' },
  'generating reply': { en: 'Drafting...', it: 'Scrivendo...', es: 'Escribiendo...' },
  
  // Simplified Priorities (No 'Priority' prefix)
  'urgent': { en: 'Urgent', it: 'Urgente', es: 'Urgente' },
  'high': { en: 'High', it: 'Alta', es: 'Alta' },
  'medium': { en: 'Medium', it: 'Media', es: 'Media' },
  'low': { en: 'Low', it: 'Bassa', es: 'Baja' },

  // Ticket Modal
  'description': { en: 'Description', it: 'Descrizione', es: 'Descripción' },
  'ai triage': { en: 'AI Triage', it: 'Triage IA', es: 'Triaje IA' },
  'attachments': { en: 'Attachments', it: 'Allegati', es: 'Adjuntos' },
  'drag drop files': { en: 'Drag & drop files here', it: 'Trascina i file qui', es: 'Arrastra y suelta archivos qui' },
  'or click to browse': { en: 'or click to browse', it: 'o clicca per sfogliare', es: 'o haz clic para buscar' },
  'selected files': { en: 'Selected Files', it: 'File Selezionati', es: 'Archivos Seleccionados' },
  'category': { en: 'Category', it: 'Categoria', es: 'Categoría' },
  'select category': { en: 'Select Category', it: 'Seleziona Categoria', es: 'Seleccionar Categoría' },
  'subcategory': { en: 'Subcategory', it: 'Sottocategoria', es: 'Subcategoría' },
  'select subcategory': { en: 'Select Subcategory', it: 'Seleziona Sottocategoria', es: 'Seleccionar Subcategoría' },
  'related asset': { en: 'Related Asset', it: 'Asset Correlato', es: 'Activo Relacionado' },
  'department': { en: 'Department', it: 'Dipartimento', es: 'Departamento' },
  'site': { en: 'Site', it: 'Sede', es: 'Sede' },
  'floor': { en: 'Floor', it: 'Piano', es: 'Planta' },
  'office': { en: 'Office', it: 'Ufficio', es: 'Oficina' },
  'contact info': { en: 'Contact Info', it: 'Contatto', es: 'Contacto' },
  
  // Ticket Categories
  'category hardware': { en: 'Hardware', it: 'Hardware', es: 'Hardware' },
  'category software': { en: 'Software', it: 'Software', es: 'Software' },
  'category network': { en: 'Network', it: 'Rete', es: 'Red' },
  'category access': { en: 'Access', it: 'Accesso', es: 'Acceso' },
  'category other': { en: 'Other', it: 'Altro', es: 'Otro' },

  // Ticket Detail
  'back to tickets': { en: 'Back to Tickets', it: 'Torna ai Ticket', es: 'Volver a Tickets' },
  'create kb article': { en: 'Create KB Article', it: 'Crea Articolo KB', es: 'Crear Artículo KB' },
  'ticket details': { en: 'Ticket Details', it: 'Dettagli Ticket', es: 'Detalles del Ticket' },
  'created at': { en: 'Created At', it: 'Creato il', es: 'Creado el' },
  'public reply': { en: 'Public Reply', it: 'Risposta Pubblica', es: 'Respuesta Pública' },
  'internal note': { en: 'Internal Note', it: 'Nota Interna', es: 'Nota Interna' },
  'add a comment': { en: 'Add a comment...', it: 'Aggiungi un commento...', es: 'Añadir un comentario...' },
  'add reply': { en: 'Add Reply', it: 'Aggiungi Risposta', es: 'Añadir Respuesta' },
  'add note': { en: 'Add Note', it: 'Aggiungi Nota', es: 'Añadir Nota' },
  'add reply and close': { en: 'Add Reply & Close', it: 'Aggiungi e Chiudi', es: 'Añadir y Cerrar' },
  'cannot close from internal note': { en: 'Cannot close a ticket from an internal note.', it: 'Non è possibile chiudere un ticket da una nota interna.', es: 'No se puede cerrar un ticket desde una nota interna.' },
  'ticket not found': { en: 'Ticket not found', it: 'Ticket non trovato', es: 'Ticket no encontrado' },
  'ticket fetch failed': { en: 'Failed to fetch ticket details.', it: 'Caricamento dettagli ticket fallito.', es: 'Error al cargar los detalles del ticket.' },

  // Assets
  'add asset': { en: 'Add Asset', it: 'Aggiungi Asset', es: 'Añadir Activo' },
  'asset search placeholder': { en: 'Search by name, model, or serial...', it: 'Cerca per nome, modello o seriale...', es: 'Buscar por nombre, modelo o serie...' },
  'asset name': { en: 'Asset Name', it: 'Nome Asset', es: 'Nombre del Activo' },
  'asset type': { en: 'Asset Type', it: 'Tipo Asset', es: 'Tipo de Activo' },
  'assigned to': { en: 'Assigned To', it: 'Assegnato A', es: 'Asignado A' },
  'purchase date': { en: 'Purchase Date', it: 'Data Acquisto', es: 'Fecha de Compra' },
  'asset tag': { en: 'Asset Tag', it: 'Tag Asset', es: 'Etiqueta de Activo' },
  'model': { en: 'Model', it: 'Modello', es: 'Modelo' },
  'serial number': { en: 'Serial Number', it: 'Numero Seriale', es: 'Número de Serie' },
  'purchase cost': { en: 'Purchase Cost', it: 'Costo Acquisto', es: 'Coste de Compra' },
  'current value': { en: 'Current Value', it: 'Valore Attuale', es: 'Valor Actual' },
  'warranty end date': { en: 'Warranty End Date', it: 'Scadenza Garanzia', es: 'Fin de Garantía' },
  'location': { en: 'Location', it: 'Posizione', es: 'Ubicación' },
  'quantity': { en: 'Quantity', it: 'Quantità', es: 'Cantidad' },
  'notes': { en: 'Notes', it: 'Note', es: 'Notas' },
  'ticket history': { en: 'Ticket History', it: 'Cronologia Ticket', es: 'Historial de Tickets' },
  'no ticket history': { en: 'No tickets associated with this asset.', it: 'Nessun ticket associato a questo asset.', es: 'No hay tickets asociados con este activo.' },
  'print qr label': { en: 'Print QR Label', it: 'Stampa Etichetta QR', es: 'Imprimir Etiqueta QR' },
  'scan to view': { en: 'Scan to view details', it: 'Scansiona per i dettagli', es: 'Escanear para ver detalles' },
  'edit asset': { en: 'Edit Asset', it: 'Modifica Asset', es: 'Editar Activo' },
  'delete asset': { en: 'Delete Asset', it: 'Elimina Asset', es: 'Eliminar Activo' },
  'asset saved successfully': { en: 'Asset saved successfully!', it: 'Asset salvato con successo!', es: '¡Activo guardado correctamente!' },
  'archive asset': { en: 'Archive Asset', it: 'Archivia Asset', es: 'Archivar Activo' },
  'unarchive asset': { en: 'Unarchive Asset', it: 'Ripristina Asset', es: 'Desarchivar Activo' },
  'confirm delete asset': { en: 'Are you sure you want to delete this asset? This action cannot be undone.', it: 'Sei sicuro di voler eliminare questo asset? Questa azione non può essere annullata.', es: '¿Estás seguro de que quieres eliminar este activo? Esta acción no se puede deshacer.' },
  'confirm archive asset': { en: 'Are you sure you want to archive this asset?', it: 'Sei sicuro di voler archiviare questo asset?', es: '¿Estás seguro de que quieres archivar este activo?' },
  'confirm unarchive asset': { en: 'Are you sure you want to unarchive this asset?', it: 'Sei sicuro di voler ripristinare questo asset?', es: '¿Estás seguro de que quieres desarchivar este activo?' },
  'archive': { en: 'Archive', it: 'Archivia', es: 'Archivar' },
  'unarchive': { en: 'Unarchive', it: 'Ripristina', es: 'Desarchivar' },
  'asset not found': { en: 'Asset not found', it: 'Asset non trovato', es: 'Activo no encontrado' },
  'recalculate depreciation': { en: 'Recalculate Depreciation', it: 'Ricalcola Ammortamento', es: 'Recalcular Depreciación' },
  'warranty lifetime': { en: 'Lifetime', it: 'A Vita', es: 'De por Vida' },
  'warranty status': { en: 'Warranty Status', it: 'Stato Garanzia', es: 'Estado de Garantía' },
  'phone number': { en: 'Phone Number', it: 'Numero di Telefono', es: 'Número de Teléfono' },
  'carrier': { en: 'Carrier', it: 'Operatore', es: 'Operador' },
  'sim serial': { en: 'SIM Serial', it: 'Seriale SIM', es: 'Serie SIM' },
  'esim serial': { en: 'eSIM Serial', it: 'Seriale eSIM', es: 'Serie eSIM' },
  'asset image': { en: 'Asset Image', it: 'Immagine Asset', es: 'Imagen del Activo' },
  'upload image': { en: 'Upload Image', it: 'Carica Immagine', es: 'Subir Imagen' },
  'image url': { en: 'Image URL', it: 'URL Immagine', es: 'URL de la Imagen' },
  'remove image': { en: 'Remove Image', it: 'Rimuovi Immagine', es: 'Eliminar Imagen' },
  'image preview': { en: 'Image Preview', it: 'Anteprima Immagine', es: 'Vista Previa de la Imagen' },
  'browse files': { en: 'Browse Files', it: 'Sfoglia File', es: 'Explorar Archivos' },
  'error assignee id missing': { en: 'Could not find the assigned user. Please try again.', it: 'Impossibile trovare l\'utente assegnato. Riprova.', es: 'No se pudo encontrar el usuario asignado. Inténtalo de nuevo.' },
  'error quantity missing': { en: 'Could not find the quantity. Please try again.', it: 'Impossibile trovare la quantità. Riprova.', es: 'No se pudo encontrar la quantità. Inténtalo de nuevo.' },

  // Licenses
  'new license': { en: 'New License', it: 'Nuova Licenza', es: 'Nueva Licencia' },
  'license name': { en: 'License Name', it: 'Nome Licenza', es: 'Nombre de Licencia' },
  'software': { en: 'Software', it: 'Software', es: 'Software' },
  'total seats': { en: 'Total Seats', it: 'Postazioni Totali', es: 'Asientos Totales' },
  'seats status': { en: 'Seats Status', it: 'Stato Postazioni', es: 'Estado de Asientos' },
  'total cost': { en: 'Total Cost', it: 'Costo Totale', es: 'Coste Total' },
  'cost per seat': { en: 'Cost Per Seat', it: 'Costo per Postazione', es: 'Coste por Asiento' },
  'sum of seat costs': { en: 'Total per Seat', it: 'Totale per Postazione', es: 'Total por Asiento' },
  'expiration date': { en: 'Expiration Date', it: 'Data di Scadenza', es: 'Fecha de Vencimiento' },
  'expires': { en: 'Expires', it: 'Scade', es: 'Vence' },
  'active': { en: 'Active', it: 'Attiva', es: 'Activa' },
  'expired': { en: 'Expired', it: 'Scaduta', es: 'Vencida' },
  'search by name or software': { en: 'Search by name or software', it: 'Cerca per nome o software', es: 'Buscar por nombre o software' },
  'expiration status active': { en: 'Active', it: 'Attiva', es: 'Activa' },
  'expiration status expired': { en: 'Expired', it: 'Scaduta', es: 'Vencida' },
  'low licenses': { en: 'Low Seats', it: 'Postazioni in Esaurimento', es: 'Pocos Asientos' },
  'assigned users': { en: 'Assigned Users', it: 'Utenti Assegnati', es: 'Usuarios Asignados' },
  'used': { en: 'Used', it: 'Usate', es: 'Usados' },
  'total': { en: 'Total', it: 'Totali', es: 'Total' },
  'unassign': { en: 'Unassign', it: 'Rimuovi Assegnazione', es: 'Desasignar' },
  'assign user': { en: 'Assign User', it: 'Assegna Utente', es: 'Asignar Usuario' },
  'assign': { en: 'Assign', it: 'Assegna', es: 'Asignar' },
  'select user': { en: 'Select User', it: 'Seleziona Utente', es: 'Seleccionar Usuario' },
  'no users assigned': { en: 'No users assigned to this license.', it: 'Nessun utente assegnato a questa licenza.', es: 'Ningún usuario asignado a esta licencia.' },
  'edit license': { en: 'Edit License', it: 'Modifica Licenza', es: 'Editar Licencia' },
  'delete license': { en: 'Delete License', it: 'Elimina Licenza', es: 'Eliminar Licencia' },
  'confirm delete license': { en: 'Are you sure you want to delete this license?', it: 'Sei sicuro di voler eliminare questa licenza?', es: '¿Estás seguro de que quieres eliminar esta licencia?' },
  'delete warning': { en: 'This action cannot be undone.', it: 'Questa azione non può essere annullata.', es: 'Esta acción no se puede deshacer.' },
  'license not found': { en: 'License not found', it: 'Licenza non trovata', es: 'Licencia no encontrada' },
  'confirm unassign user': { en: 'Are you sure you want to remove this user assignment?', it: 'Sei sicuro di voler rimuovere l\'assegnazione di questo utente?', es: '¿Estás seguro de que quieres eliminar esta asignación de usuario?' },
  'average cost per user': { en: 'Average Cost / User', it: 'Costo Medio / Utente', es: 'Coste Medio / Usuario' },
  'license details': { en: 'License Details', it: 'Dettagli Licenza', es: 'Detalles de la Licencia' },

  // Incidents
  'create incident': { en: 'Create Incident', it: 'Crea Incidente', es: 'Crear Incidente' },
  'edit incident': { en: 'Edit Incident', it: 'Modifica Incidente', es: 'Editar Incidente' },
  'incident search placeholder': { en: 'Search incidents...', it: 'Cerca incidenti...', es: 'Buscar incidentes...' },
  'severity': { en: 'Severity', it: 'Gravità', es: 'Gravedad' },
  'severity critical': { en: 'Critical', it: 'Critica', es: 'Crítica' },
  'severity high': { en: 'High', it: 'Alta', es: 'Alta' },
  'severity medium': { en: 'Medium', it: 'Media', es: 'Media' },
  'severity low': { en: 'Low', it: 'Bassa', es: 'Baja' },
  'reporter': { en: 'Reporter', it: 'Segnalatore', es: 'Informador' },
  'impact analysis': { en: 'Impact Analysis', it: 'Analisi dell\'Impatto', es: 'Análisis de Impacto' },
  'root cause analysis': { en: 'Root Cause Analysis', it: 'Analisi delle Cause Principali', es: 'Análisis de Causa Raíz' },
  'solution': { en: 'Solution', it: 'Soluzione', es: 'Solución' },
  'incident details': { en: 'Incident Details', it: 'Dettagli Incidente', es: 'Detalles del Incidente' },
  'timeline': { en: 'Timeline', it: 'Cronologia', es: 'Línea de Tiempo' },
  'analysis': { en: 'Analysis', it: 'Analisi', es: 'Análisis' },
  'add timeline update placeholder': { en: 'Add an update...', it: 'Aggiungi un aggiornamento...', es: 'Añadir una actualización...' },
  'add update': { en: 'Add Update', it: 'Aggiungi Aggiornamento', es: 'Añadir Actualización' },
  'generate post mortem ai': { en: 'Generate Post-Mortem (AI)', it: 'Genera Post-Mortem (IA)', es: 'Generar Post-Mortem (IA)' },
  'incident not documented': { en: 'Not documented yet.', it: 'Non ancora documentato.', es: 'Aún no documentado.' },
  'resolve incident': { en: 'Resolve Incident', it: 'Risolvi Incidente', es: 'Resolver Incidente' },
  'resolve incident prompt kb': { en: 'Do you want to create a Knowledge Base article from this incident?', it: 'Vuoi creare un articolo della Knowledge Base da questo incidente?', es: '¿Quieres crear un artículo de la Base de Conocimiento a partir de este incidente?' },
  'no just resolve': { en: 'No, just resolve', it: 'No, risolvi solo', es: 'No, solo resolver' },
  'yes create kb': { en: 'Yes, create KB', it: 'Sì, crea KB', es: 'Sí, crear KB' },
  'kb from incident template': { en: 'Incident #{id}: {description}\n\nResolution:\n{solution}', it: 'Incidente #{id}: {description}\n\nRisoluzione:\n{solution}', es: 'Incidente #{id}: {description}\n\nResolución:\n{solution}' },
  'timeline entry creation': { en: 'Incident created by {author}.', it: 'Incidente creato da {author}.', es: 'Incidente creado por {author}.' },
  'incident not found': { en: 'Incident not found', it: 'Incidente non trovato', es: 'Incidente no encontrado' },
  'tags comma separated': { en: 'Tags (comma separated)', it: 'Tag (separati da virgola)', es: 'Etiquetas (separadas por comas)' },

  // Knowledge Base
  'create article': { en: 'Create Article', it: 'Crea Articolo', es: 'Crear Artículo' },
  'edit article': { en: 'Edit Article', it: 'Modifica Articolo', es: 'Editar Artículo' },
  'kb search placeholder': { en: 'Search knowledge base...', it: 'Cerca nella knowledge base...', es: 'Buscar en la base de conocimiento...' },
  'no articles found': { en: 'No articles found.', it: 'Nessun articolo trovato.', es: 'No se encontraron artículos.' },
  'last updated': { en: 'Last updated', it: 'Ultimo aggiornamento', es: 'Última actualización' },
  'tags': { en: 'Tags', it: 'Tag', es: 'Etiquetas' },
  'access denied': { en: 'Access Denied', it: 'Accesso Negato', es: 'Acceso Denegado' },
  'no permission to view': { en: 'You do not have permission to view this article.', it: 'Non hai il permesso di visualizzare questo articolo.', es: 'No tienes permiso para ver este artículo.' },
  'back to kb': { en: 'Back to Knowledge Base', it: 'Torna alla Knowledge Base', es: 'Volver a la Base de Conocimiento' },
  'delete article': { en: 'Delete Article', it: 'Elimina Articolo', es: 'Eliminar Artículo' },
  'delete confirmation': { en: 'Are you sure you want to delete this article?', it: 'Sei sicuro di voler eliminare questo articolo?', es: '¿Estás seguro de que quieres eliminar questo articolo?' },
  'publish article': { en: 'Publish Article', it: 'Pubblica Articolo', es: 'Publicar Artículo' },
  'title': { en: 'Title', it: 'Titolo', es: 'Título' },
  'content': { en: 'Content', it: 'Contenuto', es: 'Contenido' },
  'visible to': { en: 'Visible To', it: 'Visibile A', es: 'Visible Para' },
  'kb auto translate note': { en: 'Content will be automatically translated to other languages when saving if left empty.', it: 'Il contenuto verrà tradotto automaticamente nelle altre lingue al salvataggio se lasciato vuoto.', es: 'El contenido se traducirá automáticamente a otros idiomas al guardar si se deja vacío.' },
  'translate': { en: 'Translate', it: 'Traduci', es: 'Traducir' },
  'ai assistant': { en: 'AI Assistant', it: 'Assistente IA', es: 'Asistente IA' },
  'ai action generate': { en: 'Generate Content', it: 'Genera Contenuto', es: 'Generar Contenido' },
  'ai action correct': { en: 'Correct Grammar', it: 'Correggi Grammatica', es: 'Corregir Gramática' },
  'ai action complete': { en: 'Complete Text', it: 'Completa Testo', es: 'Completar Texto' },
  'kb editor translate failed': { en: 'Failed to translate {field}.', it: 'Traduzione di {field} fallita.', es: 'Error al traducir {field}.' },
  'kb editor provide title for ai': { en: 'Please provide a title first.', it: 'Per favore, fornisci prima un titolo.', es: 'Por favor, proporciona un título primero.' },
  'kb editor provide content for ai': { en: 'Please provide some content first.', it: 'Per favore, fornisci prima del contenuto.', es: 'Por favor, proporciona algo de contenido primero.' },
  'kb editor ai failed': { en: 'AI assistance failed.', it: 'Assistenza IA fallita.', es: 'La asistencia de IA falló.' },
  'kb editor save error required': { en: 'Title, Content, Category, and Audience are required.', it: 'Titolo, Contenuto, Categoria e Pubblico sono obbligatori.', es: 'Título, Contenido, Categoría y Audiencia son obligatorios.' },
  'kb editor save failed': { en: 'Failed to save article: {error}', it: 'Salvataggio articolo fallito: {error}', es: 'Error al guardar el artículo: {error}' },
  'kb category troubleshooting': { en: 'Troubleshooting', it: 'Risoluzione Problemi', es: 'Solución de Problemas' },
  'kb category policies': { en: 'Policies', it: 'Policy', es: 'Políticas' },
  'kb category how-to': { en: 'How-To', it: 'Guide', es: 'Guías' },
  'kb category general': { en: 'General', it: 'Generale', es: 'General' },
  'kb category security': { en: 'Security', it: 'Sicurezza', es: 'Seguridad' },
  'kb category onboarding': { en: 'Onboarding', it: 'Onboarding', es: 'Incorporación' },
  
  // AI Assistant Chat
  'type your question': { en: 'Type your question...', it: 'Scrivi la tua domanda...', es: 'Escribe tu pregunta...' },
  'ai assistant connection error': { en: 'Failed to connect to AI service.', it: 'Impossibile connettersi al servizio IA.', es: 'Error al conectar con el servicio de IA.' },

  // SLA Policies (Only unique definitions here)
  'priority column': { en: 'Priority', it: 'Priorità', es: 'Prioridad' },
  'first response time': { en: 'First Response Time (Minutes)', it: 'Tempo Prima Risposta (Minuti)', es: 'Tiempo de Primera Respuesta (Minutos)' },
  'resolution time': { en: 'Resolution Time (Minutes)', it: 'Tempo Risoluzione (Minuti)', es: 'Tiempo de Resolución (Minutos)' },
  'sla policy saved': { en: 'SLA Policies saved successfully.', it: 'Policy SLA salvate con successo.', es: 'Políticas de SLA guardadas correctamente.' },
  'failed to load sla policies': { en: 'Failed to load SLA policies.', it: 'Caricamento policy SLA fallito.', es: 'Error al cargar las políticas de SLA.' },
  'failed to save sla policies': { en: 'Failed to save SLA policies.', it: 'Salvataggio policy SLA fallito.', es: 'Error al guardar las políticas de SLA.' },

  // Backup & Restore (Only unique definitions here)
  'backup': { en: 'Backup', it: 'Backup', es: 'Copia de Seguridad' },
  'create backup': { en: 'Create Backup', it: 'Crea Backup', es: 'Crear Copia de Seguridad' },
  'restore': { en: 'Restore', it: 'Ripristina', es: 'Restaurar' },
  'upload backup': { en: 'Upload Backup', it: 'Carica Backup', es: 'Subir Copia de Seguridad' },
  'backup success': { en: 'Backup created successfully.', it: 'Backup creato con successo.', es: 'Copia de seguridad creada correctamente.' },
  'restore warning': { en: 'Restoring will overwrite current data. Continue?', it: 'Il ripristino sovrascriverà i dati attuali. Continuare?', es: 'La restauración sobrescribirá los datos actuales. ¿Continuar?' },
  'restore success': { en: 'Data restored successfully.', it: 'Dati ripristinati con successo.', es: 'Datos restaurados correctamente.' },
  'restore failed': { en: 'Restore failed. Invalid file format.', it: 'Ripristino fallito. Formato file non valido.', es: 'Restauración fallida. Formato de archivo inválido.' },
};
